### PR TITLE
Fix Before Job snapshots for pipelines

### PR DESCRIPTION
**Pull request by mjeanson**
This is a fix similar to "JENKINS-50552: Fix triggering snapshot
reverts" but for the 'Before Job' snapshots. It allows to add stages to a
pipeline with an 'agent' directive and have the 'Before Job' snapshot
reverted on the node before each of these stage.

As part of the change I revert "slave: remove circular dependency in
disconnect path" as on our systems it completely broke any job running
on a libvirt node. I hope I fixed the issue this commit was targeting by
removing 'ComputerUtils.disconnect()' from the disconnect method of
VirtualMachineSlaveComputer. This was causing a recursion of disconnects
in my testing. However I can't really be sure it mitigates the original
issue since we never experienced it on our systems. Your testing would
be appreciated.

The main part of the change is to remove
LibvirtSnapshotRevertRunListener and replace it with a new 
TaskListener.taskAccepted method in VirtualMachineSlaveComputer.

I also added new OfflineClauses so that when we disconnect to apply a
'Before Job' snapshot we don't also apply a 'Revert' snapshot first if
configured.

Some ancilary fixes and logging improvements are included in separate commits.

### Testing done

Tested on a development system with a single VM. It's alse used in a production Jenkins instance at "https://ci.lttng.org" with multiple VMs and a mix of pipelines and traditionnal jobs.

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by bgermann** [comment]
Thanks for this very well documented change set! I do no longer use the plugin myself and would like to ask you if you want to take it over.

**Comment by mjeanson** [comment]
If it's unmaintained at the moment I suppose I could give it a shot. Are any of the co-maintainers active?

**Comment by bgermann** [comment]
No. The last thing I did was making sure that the plugin auto-build works fine. It used to be that one had to publish a built version manually. So taking over should not be too much of a pain. I am going to file a request to give you access later today.

**Comment by mjeanson** [comment]
I created a new jenkins.io account 'm_jeanson' as I don't have access to the email associated with 'mjeanson' over there.

**Comment by bgermann** [comment]
Please log in to Artifactory and Jira as described in the prerequisites for [adding a plugin developer](https://github.com/bgermann/repository-permissions-updater#requesting-permissions).

**Comment by mjeanson** [comment]
I logged in both systems with the 'm_jeanson' account.

**Comment by bgermann** [comment]
You should be set up. Please add yourself to the developers in pom.xml

**Comment by mjeanson** [comment]
Do you know if I should use my github or jenkins.io username for the <id> tag in the pom?

**Comment by bgermann** [comment]
jenkins.io

**Pull request merged**
